---
services:
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    volumes:
      - "./localstack_data:/var/lib/localstack"
      - "./init-localstack.sh:/etc/localstack/init/ready.d/init-localstack.sh"
