---
services:
  localstack:
    image: localstack/localstack
    environment:
      DYNAMODB_SHARE_DB: 1
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    volumes:
      - "./localstack_data:/var/lib/localstack"
      - "./init-localstack.sh:/etc/localstack/init/ready.d/init-localstack.sh"

  proxy:
    ports:
      - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: eu-west-1
      AWS_ENDPOINT_URL: http://localstack:4566/
      SQS_SOURCE_QUEUE: input-queue
      SQS_DESTINATION_QUEUE: output-queue
      DDB_REQUEST_TABLE: request-ddb-table
      DDB_RESPONSE_TABLE: response-ddb-table
    build:
      context: .
    volumes:
      - .:/app
    working_dir: /app
