env: dev

server:
  port: 8080

backend_type: sqs

aws:
  access_key_id: default
  secret_access_key: default
  region: eu-west-1
  endpoint_url: http://localstack:4566/
sqs:
  source_queue: input-queue
  destination_queue: result-queue
ddb:
  request-table: request-ddb-table
  response-table: response-ddb-table
